#!/bin/sh
# Regenerates console_init.sh from the two source files, so the installer can
# never drift from what is actually tested.
set -e
cd "$(dirname "$0")"
OUT=console_init.sh

{
    echo "#!/bin/sh"
    echo "# Generated by make_console_init.sh - do not edit by hand."
    echo "# Paste this whole file into the router console (or scp + sh it)."
    echo ""
    echo "cat > /root/tplink_crypto.awk << 'TPLINK_CRYPTO_AWK_EOF'"
    cat tplink_crypto.awk
    echo "TPLINK_CRYPTO_AWK_EOF"
    echo ""
    echo "cat > /root/tplink_router_monitor.sh << 'TPLINK_MONITOR_SH_EOF'"
    cat tplink_router_monitor.sh
    echo "TPLINK_MONITOR_SH_EOF"
    echo ""
    cat << 'TAIL_EOF'
cat > /root/tplink_auto_refill.sh << 'EOF'
#!/bin/sh
if ping -c 1 -W 2 192.168.1.1 >/dev/null 2>&1; then
    ( /root/tplink_router_monitor.sh ) &
    ( sleep 30; /root/tplink_router_monitor.sh ) &
    # ( sleep 40; /root/tplink_router_monitor.sh ) &
    wait
fi
EOF

chmod +x /root/tplink_router_monitor.sh /root/tplink_auto_refill.sh

# sanity check: the crypto must agree with the FIPS-197 test vectors here,
# on this awk, before anything is scheduled
if [ "$(awk -v mode=selftest -f /root/tplink_crypto.awk < /dev/null)" != "ok" ]; then
    echo "ERROR: crypto selftest failed on this device's awk - not installing cron" >&2
    exit 1
fi

(crontab -l 2>/dev/null | grep -Fv "tplink_auto_refill.sh"; echo "* * * * * /root/tplink_auto_refill.sh") | crontab -

/etc/init.d/cron restart
TAIL_EOF
} > "$OUT"

chmod +x "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
